name: Part 2 IoTDB Bisect

on:
  workflow_dispatch:

jobs:
  iotdb-bisect:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    
    steps:
    - name: Checkout idoft
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Clone IoTDB
      run: |
        cd $HOME
        git clone https://github.com/apache/iotdb
        cd iotdb
        git checkout f94f99a48281519ddf156ba67cd1825d1491557c
        echo "=== Checked out known flaky commit ==="
        git log --oneline -1
    
    - name: Test at known flaky commit
      run: |
        cd $HOME/iotdb
        echo "=== Testing at known flaky SHA ==="
        
        mvn clean install -DskipTests -pl iotdb-core/datanode -am -Dcheckstyle.skip=true -Denforcer.skip=true 2>&1 | tee compile-known.log
        
        if ! grep -q "BUILD SUCCESS" compile-known.log; then
          echo "ERROR: Cannot compile"
          exit 1
        fi
        
        mvn -pl iotdb-core/datanode test -Dtest=org.apache.iotdb.db.queryengine.plan.planner.distribution.AlignByDeviceOrderByLimitOffsetTest#orderByTimeTest2 2>&1 | tee test-normal.log
        
        mvn -pl iotdb-core/datanode edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.iotdb.db.queryengine.plan.planner.distribution.AlignByDeviceOrderByLimitOffsetTest#orderByTimeTest2 -DnondexRuns=30 2>&1 | tee test-nondex-known.log
        
        if grep -q "There are test failures" test-nondex-known.log; then
          echo "✓ Test IS flaky"
        fi
    
    - name: Find test creation commit
      id: test_created
      run: |
        cd $HOME/iotdb
        FIRST_COMMIT=$(git log --all --oneline --diff-filter=A -- "**/AlignByDeviceOrderByLimitOffsetTest.java" | tail -1 | awk '{print $1}')
        if [ -z "$FIRST_COMMIT" ]; then
          FIRST_COMMIT=$(git rev-parse HEAD~500)
        fi
        echo "first_commit=$FIRST_COMMIT" >> $GITHUB_OUTPUT
        git log --oneline -1 $FIRST_COMMIT
    
    - name: Run git bisect
      run: |
        cd $HOME/iotdb
        GOOD_COMMIT="${{ steps.test_created.outputs.first_commit }}"
        BAD_COMMIT="f94f99a48281519ddf156ba67cd1825d1491557c"
        
        echo "Starting bisect: $GOOD_COMMIT (good) to $BAD_COMMIT (bad)"
        git bisect start $BAD_COMMIT $GOOD_COMMIT
        
        # Create test script
        cat > /tmp/test.sh << 'ENDSCRIPT'
        #!/bin/bash
        echo "Testing: $(git log --oneline -1)"
        mvn clean install -DskipTests -pl iotdb-core/datanode -am -Dcheckstyle.skip=true -Denforcer.skip=true > /tmp/c.log 2>&1 || exit 125
        grep -q "BUILD SUCCESS" /tmp/c.log || exit 125
        mvn -pl iotdb-core/datanode test -Dtest=org.apache.iotdb.db.queryengine.plan.planner.distribution.AlignByDeviceOrderByLimitOffsetTest#orderByTimeTest2 > /tmp/t.log 2>&1 || exit 125
        grep -q "BUILD SUCCESS" /tmp/t.log || exit 125
        mvn -pl iotdb-core/datanode edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.iotdb.db.queryengine.plan.planner.distribution.AlignByDeviceOrderByLimitOffsetTest#orderByTimeTest2 -DnondexRuns=20 > /tmp/n.log 2>&1
        if grep -q "There are test failures" /tmp/n.log; then
          echo "FLAKY"
          exit 1
        else
          echo "NOT FLAKY"
          exit 0
        fi
        ENDSCRIPT
        
        chmod +x /tmp/test.sh
        git bisect run /tmp/test.sh 2>&1 | tee bisect.log
        
        FIRST_FLAKY=$(git bisect view --oneline | head -1 | awk '{print $1}')
        echo "FIRST FLAKY COMMIT: $FIRST_FLAKY"
        git log --oneline -1 $FIRST_FLAKY
        echo "$FIRST_FLAKY" > /tmp/result.txt
        git bisect reset
    
    - name: Verify results
      run: |
        cd $HOME/iotdb
        FIRST_FLAKY=$(cat /tmp/result.txt)
        PARENT=$(git rev-parse ${FIRST_FLAKY}~1)
        
        echo "=== Testing PARENT (should be NOT flaky) ==="
        git checkout $PARENT
        git log --oneline -1
        mvn clean install -DskipTests -pl iotdb-core/datanode -am -Dcheckstyle.skip=true -Denforcer.skip=true > /dev/null 2>&1
        mvn -pl iotdb-core/datanode edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.iotdb.db.queryengine.plan.planner.distribution.AlignByDeviceOrderByLimitOffsetTest#orderByTimeTest2 -DnondexRuns=30 2>&1 | tee parent-nondex.log
        
        echo "=== Testing FIRST FLAKY ==="
        git checkout $FIRST_FLAKY
        git log --oneline -1
        mvn clean install -DskipTests -pl iotdb-core/datanode -am -Dcheckstyle.skip=true -Denforcer.skip=true > /dev/null 2>&1
        mvn -pl iotdb-core/datanode edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.iotdb.db.queryengine.plan.planner.distribution.AlignByDeviceOrderByLimitOffsetTest#orderByTimeTest2 -DnondexRuns=30 2>&1 | tee flaky-nondex.log
        
        echo "================================"
        echo "PART 2 COMPLETE!"
        echo "First flaky commit: $FIRST_FLAKY"
        echo "URL: https://github.com/apache/iotdb/commit/$FIRST_FLAKY"
        echo "================================"
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: iotdb-bisect-results
        path: |
          /home/runner/iotdb/*.log
          /tmp/result.txt
