name: Test Flaky Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-flaky:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Clone swagger-core repository
      run: |
        cd $HOME
        git clone https://github.com/swagger-api/swagger-core
        cd swagger-core
        git checkout master
        echo "Current commit: $(git rev-parse HEAD)"
    
    - name: Compile the project
      run: |
        cd $HOME/swagger-core
        mvn clean install -DskipTests -pl modules/swagger-jaxrs2 -am -Drat.skip -Dlicense.skip=true -Dcheckstyle.skip
    
    - name: Run test normally (should pass)
      run: |
        cd $HOME/swagger-core
        echo "=== Running test WITHOUT NonDex (should PASS) ==="
        mvn -pl modules/swagger-jaxrs2 test -Dtest=io.swagger.v3.jaxrs2.annotations.operations.AnnotatedOperationMethodTest#testOperationWithResponseExamples
    
    - name: Run test with NonDex (checking for flakiness)
      run: |
        cd $HOME/swagger-core
        echo "=== Running test WITH NonDex (checking if FLAKY) ==="
        mvn -pl modules/swagger-jaxrs2 edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=io.swagger.v3.jaxrs2.annotations.operations.AnnotatedOperationMethodTest#testOperationWithResponseExamples -DnondexRuns=10
      continue-on-error: true
    
    - name: Summary
      run: |
        echo "=== Test Flakiness Check Complete ==="
        echo "If the NonDex step failed, the test is flaky!"
        echo "Check the logs above to see the test results."
