name: Part 3 - JBPM Flaky Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-jbpm-flaky:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Clone and compile jbpm repository
      run: |
        cd $HOME
        git clone https://github.com/kiegroup/jbpm
        cd jbpm
        git checkout f7e80e82b7670c09485ce83869a287ef51dcbb59
        echo "=== Checked out commit ==="
        git log --oneline -1
        
        echo "=== Compiling JBPM ==="
        mvn clean install -DskipTests \
          -pl jbpm-case-mgmt/jbpm-case-mgmt-impl,jbpm-services/jbpm-kie-services \
          -am \
          -Drat.skip=true \
          -Dlicense.skip=true \
          -Dcheckstyle.skip=true \
          -Denforcer.skip=true \
          -Dmaven.javadoc.skip=true \
          2>&1 | tee compile.log
        
        if ! grep -q "BUILD SUCCESS" compile.log; then
          echo "ERROR: Compilation failed"
          exit 1
        fi
        echo "✓ Compilation successful"
    
    - name: Test 1 - testStartThenReopenActiveCase
      continue-on-error: true
      run: |
        cd $HOME/jbpm
        echo "=========================================="
        echo "TEST 1: testStartThenReopenActiveCase"
        echo "=========================================="
        
        # Run without NonDex (should pass)
        echo "--- Running without NonDex ---"
        mvn -pl jbpm-case-mgmt/jbpm-case-mgmt-impl test \
          -Dtest=org.jbpm.casemgmt.impl.CaseServiceImplTest#testStartThenReopenActiveCase \
          2>&1 | tee test1-normal.log
        
        if grep -q "BUILD SUCCESS" test1-normal.log; then
          echo "✓ Test passes without NonDex"
        else
          echo "✗ Test fails without NonDex - skipping NonDex run"
          exit 0
        fi
        
        # Run with NonDex (should fail if flaky)
        echo "--- Running with NonDex ---"
        mvn -pl jbpm-case-mgmt/jbpm-case-mgmt-impl \
          edu.illinois:nondex-maven-plugin:2.1.1:nondex \
          -Dtest=org.jbpm.casemgmt.impl.CaseServiceImplTest#testStartThenReopenActiveCase \
          -DnondexRuns=50 \
          2>&1 | tee test1-nondex.log
        
        if grep -q "There are test failures" test1-nondex.log; then
          echo "✓✓✓ TEST 1 IS FLAKY! ✓✓✓"
          echo "FLAKY_TEST=test1" >> $GITHUB_ENV
        else
          echo "Test 1 not flaky in this run"
        fi
    
    - name: Test 2 - testCaseWithRequiredRestrictedCaseFileItem
      continue-on-error: true
      if: env.FLAKY_TEST == ''
      run: |
        cd $HOME/jbpm
        echo "=========================================="
        echo "TEST 2: testCaseWithRequiredRestrictedCaseFileItem"
        echo "=========================================="
        
        echo "--- Running without NonDex ---"
        mvn -pl jbpm-case-mgmt/jbpm-case-mgmt-impl test \
          -Dtest=org.jbpm.casemgmt.impl.CaseServiceImplTest#testCaseWithRequiredRestrictedCaseFileItem \
          2>&1 | tee test2-normal.log
        
        if grep -q "BUILD SUCCESS" test2-normal.log; then
          echo "✓ Test passes without NonDex"
        else
          echo "✗ Test fails without NonDex - skipping NonDex run"
          exit 0
        fi
        
        echo "--- Running with NonDex ---"
        mvn -pl jbpm-case-mgmt/jbpm-case-mgmt-impl \
          edu.illinois:nondex-maven-plugin:2.1.1:nondex \
          -Dtest=org.jbpm.casemgmt.impl.CaseServiceImplTest#testCaseWithRequiredRestrictedCaseFileItem \
          -DnondexRuns=50 \
          2>&1 | tee test2-nondex.log
        
        if grep -q "There are test failures" test2-nondex.log; then
          echo "✓✓✓ TEST 2 IS FLAKY! ✓✓✓"
          echo "FLAKY_TEST=test2" >> $GITHUB_ENV
        else
          echo "Test 2 not flaky in this run"
        fi
    
    - name: Test 3 - testAddMultipleDynamicTasksToStage
      continue-on-error: true
      if: env.FLAKY_TEST == ''
      run: |
        cd $HOME/jbpm
        echo "=========================================="
        echo "TEST 3: testAddMultipleDynamicTasksToStage"
        echo "=========================================="
        
        echo "--- Running without NonDex ---"
        mvn -pl jbpm-case-mgmt/jbpm-case-mgmt-impl test \
          -Dtest=org.jbpm.casemgmt.impl.CaseDynamicNodesTest#testAddMultipleDynamicTasksToStage \
          2>&1 | tee test3-normal.log
        
        if grep -q "BUILD SUCCESS" test3-normal.log; then
          echo "✓ Test passes without NonDex"
        else
          echo "✗ Test fails without NonDex - skipping NonDex run"
          exit 0
        fi
        
        echo "--- Running with NonDex ---"
        mvn -pl jbpm-case-mgmt/jbpm-case-mgmt-impl \
          edu.illinois:nondex-maven-plugin:2.1.1:nondex \
          -Dtest=org.jbpm.casemgmt.impl.CaseDynamicNodesTest#testAddMultipleDynamicTasksToStage \
          -DnondexRuns=50 \
          2>&1 | tee test3-nondex.log
        
        if grep -q "There are test failures" test3-nondex.log; then
          echo "✓✓✓ TEST 3 IS FLAKY! ✓✓✓"
          echo "FLAKY_TEST=test3" >> $GITHUB_ENV
        else
          echo "Test 3 not flaky in this run"
        fi
    
    - name: Test 4 - testTimerNameAndTimerId
      continue-on-error: true
      if: env.FLAKY_TEST == ''
      run: |
        cd $HOME/jbpm
        echo "=========================================="
        echo "TEST 4: testTimerNameAndTimerId"
        echo "=========================================="
        
        echo "--- Running without NonDex ---"
        mvn -pl jbpm-services/jbpm-kie-services test \
          -Dtest=org.jbpm.kie.services.impl.admin.ProcessInstanceAdminServiceImplTest#testTimerNameAndTimerId \
          2>&1 | tee test4-normal.log
        
        if grep -q "BUILD SUCCESS" test4-normal.log; then
          echo "✓ Test passes without NonDex"
        else
          echo "✗ Test fails without NonDex - skipping NonDex run"
          exit 0
        fi
        
        echo "--- Running with NonDex ---"
        mvn -pl jbpm-services/jbpm-kie-services \
          edu.illinois:nondex-maven-plugin:2.1.1:nondex \
          -Dtest=org.jbpm.kie.services.impl.admin.ProcessInstanceAdminServiceImplTest#testTimerNameAndTimerId \
          -DnondexRuns=50 \
          2>&1 | tee test4-nondex.log
        
        if grep -q "There are test failures" test4-nondex.log; then
          echo "✓✓✓ TEST 4 IS FLAKY! ✓✓✓"
          echo "FLAKY_TEST=test4" >> $GITHUB_ENV
        else
          echo "Test 4 not flaky in this run"
        fi
    
    - name: Summary
      run: |
        echo "=========================================="
        if [ -n "$FLAKY_TEST" ]; then
          echo "✓ SUCCESS! Found flaky test: $FLAKY_TEST"
          echo "Part 3 COMPLETE"
        else
          echo "⚠ No flaky tests detected in this run"
          echo "Tests may need more NonDex runs or different tests"
        fi
        echo "=========================================="
    
    - name: Upload all logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jbpm-test-logs
        path: |
          /home/runner/jbpm/*.log
