name: Test JBPM Flaky Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-jbpm-flaky:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Clone jbpm repo
      run: |
        cd $HOME
        git clone https://github.com/kiegroup/jbpm
        cd jbpm
        echo "Switched to jbpm repo."
        git checkout master || git checkout main
        echo "Current commit: $(git rev-parse HEAD)"

    - name: Build jbpm (skip tests)
      run: |
        cd $HOME/jbpm
        echo "Building jbpm with tests skipped..."
        mvn clean install -DskipTests \
          -pl jbpm-case-mgmt/jbpm-case-mgmt-impl -am \
          -Drat.skip -Dlicense.skip=true -Dcheckstyle.skip -Denforcer.skip=true

    - name: Run test normally (expected to pass)
      run: |
        cd $HOME/jbpm
        echo "=== Running test without NonDex (expected to PASS) ==="
        mvn -pl jbpm-case-mgmt/jbpm-case-mgmt-impl test \
          -Dtest=org.jbpm.casemgmt.impl.CaseServiceImplTest#testStartThenReopenActiveCase

    - name: Run test with NonDex (flakiness check)
      run: |
        cd $HOME/jbpm
        echo "=== Running test with NonDex (checking for flakiness) ==="
        mvn -pl jbpm-case-mgmt/jbpm-case-mgmt-impl \
          edu.illinois:nondex-maven-plugin:2.1.1:nondex \
          -Dtest=org.jbpm.casemgmt.impl.CaseServiceImplTest#testStartThenReopenActiveCase \
          -DnondexRuns=50
      continue-on-error: true

    - name: Summary
      run: |
        echo "=== Flakiness Check Complete ==="
        echo "If the NonDex step failed, the test might be flaky."
        echo "Review the logs above for details."
